### ISSUE TITLE
Considering a more detailed example?

### ISSUE THREAD

**Issue by Shengguang-Zhou** [PhyscalX/gradio-image-prompter#1]
Thanks a lot for such a life saving great project! As so many people are looking for a gradio image prompter tool, do you consider make it more readable with a detailed documentation and examples? Thanks!

**Comment by PhyscalX** [comment]
Hi, @Shengguang-Zhou
We aim to provide the simplest example following the official demo style.
You can directly refer the official documentation for [Custom Components](https://www.gradio.app/guides/custom-components-in-five-minutes), [Backend](https://www.gradio.app/guides/backend) and [Frontend](https://www.gradio.app/guides/frontend).
