### ISSUE TITLE
Coordinate not handling correctly when the image is updated from another tab

### ISSUE THREAD

**Issue by kexul** [PhyscalX/gradio-image-prompter#3]
Hi @PhyscalX , I find a wired bug that the coordinate is not handling correctly when the image is updated from another tab. 

Here is a minimal example:
```python
from gradio_image_prompter import ImagePrompter
import gradio as gr
from PIL import Image
import numpy as np 


def crop_image(image_prompter):
    image = image_prompter['image']
    image = np.array(Image.open(image))
    points = image_prompter['points']
    box = None
    for item in points:
        if item[2] == 2:
            box = [item[0], item[1], item[3], item[4]]
    box = list(map(int, box))
    part = image[box[1]:box[3], box[0]:box[2], :]
    return part
    
def set_image():
    path = 'test_image/cat.jpg'
    return {'image':path}

with gr.Blocks() as demo:
    with gr.Tab('1'):
        set_btn = gr.Button('Set Image')
    with gr.Tab('2'):
        with gr.Row():
            prompter = ImagePrompter(height=666, type='filepath')
            image = gr.Image(type='numpy', label='Image')
        with gr.Row():
            crop_btn = gr.Button('crop')

    set_btn.click(set_image, inputs=None, outputs=prompter)
    crop_btn.click(crop_image, inputs=prompter, outputs=image)


demo.launch(server_name='0.0.0.0')

```

Here is a screenshot when the height is fixed `prompter = ImagePrompter(height=666, type='filepath')`:
![cat](https://github.com/PhyscalX/gradio-image-prompter/assets/5920217/5a8e37aa-da26-4d9d-a23f-edb24e6d124c)
Another screenshot when the height is not defined `prompter = ImagePrompter(type='filepath')`:
https://github.com/PhyscalX/gradio-image-prompter/assets/5920217/6dd38bb2-a419-4776-bb2f-a8d99d20a083

**Comment by PhyscalX** [comment]
Hi, @kexul 

1. We initialize ``box_drawer`` with the original image size on  image loading. [[Code]](https://github.com/PhyscalX/gradio-image-prompter/blob/b568e497559e334c8fb51818802e9c11ad92e5bd/frontend/shared/ImageUploader.svelte#L23).
2. As a result, setting the custom component size is NOT supported.
3. You put this component and ``gr.Image`` under the same row, the varied crop size will also break the component size.

**Comment by kexul** [comment]
> when As a result, setting the custom component size is NOT supported.

Hi @PhyscalX , when the image is update from the same tab, this demo runs fine. 
![cat4](https://github.com/PhyscalX/gradio-image-prompter/assets/5920217/213606c0-43cf-40e8-840d-d9ec82f9c2a6)
```python
from gradio_image_prompter import ImagePrompter
import gradio as gr
from PIL import Image
import numpy as np 


def crop_image(image_prompter):
    image = image_prompter['image']
    image = np.array(Image.open(image))
    points = image_prompter['points']
    box = None
    for item in points:
        if item[2] == 2:
            box = [item[0], item[1], item[3], item[4]]
    box = list(map(int, box))
    part = image[box[1]:box[3], box[0]:box[2], :]
    return part
    
def set_image():
    path = 'test_image/cat.jpg'
    return {'image':path}

with gr.Blocks() as demo:
    with gr.Row():
        prompter = ImagePrompter(type='filepath', height=666, sources=[])
        image = gr.Image(type='numpy', label='Image')
    with gr.Row():
        set_btn = gr.Button('Set Image')
        crop_btn = gr.Button('crop')

    set_btn.click(set_image, inputs=None, outputs=prompter)
    crop_btn.click(crop_image, inputs=prompter, outputs=image)


demo.launch(server_name='0.0.0.0')
```

**Comment by kexul** [comment]
> You put this component and gr.Image under the same row, the varied crop size will also break the component size.

Yes, when the height is not fixed, the crop size break the component size.

**Comment by PhyscalX** [comment]
It is not a ``Tab`` component issue.

Do not put the ``prompter`` and ``image`` in the same row. 
Or you should pad the crop to the original image size.

**Comment by kexul** [comment]
Hi @PhyscalX, thanks for your reply! Would you mind elaborate on the best way to set up a side-by-side layout then? 
I've check your implementation here https://huggingface.co/spaces/BAAI/tokenize-anything/blob/main/app.py, it seems to be very complicated.
![图片](https://github.com/PhyscalX/gradio-image-prompter/assets/5920217/9d16a119-e13d-459c-b4bb-e582889c4069)

**Comment by PhyscalX** [comment]
Get used to it. Excessive nesting style is also complicated.

**Comment by kexul** [comment]
🤣
